name: Publish
env:
  release_version: 0.0.${{github.run_number}}

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
        
    - name: Pack
      run: dotnet pack src/SqlBulkCopyMerge/SqlBulkCopyMerge.csproj -o packaged -c Release -p:PackageVersion=$release_version -p:PackageID=stevekirks.SqlBulkCopyMerge
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: packaged
        path: packaged
        
    - name: Create github release and git tag for release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: ${release_version}
        tag_name: v${release_version}
        draft: false
        prerelease: false
        
    - name: Push to Nuget
      run: dotnet nuget push packaged/SqlBulkCopyMerge.$release_version.nupkg -k ${{ secrets.nuget_api_key }} -s https://api.nuget.org/v3/index.json
