name: Publish
env:
  release_version: ${GITHUB_REF#refs/*/}

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check output
      run: |
        echo $release_version
