name: Publish
env:
  RELEASE_VERSION: 1.0.${{github.run_number}}

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
        
    - name: Pack
      run: dotnet pack src/SqlBulkCopyMerge/SqlBulkCopyMerge.csproj -o packaged -c Release -p:PackageVersion=$RELEASE_VERSION
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: packaged
        path: packaged
        
    - name: Create github release and git tag for release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: ${{ env.RELEASE_VERSION }}
        tag_name: v${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
    
    - name: Upload package to github release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: packaged/SqlBulkCopyMerge.${{ env.RELEASE_VERSION }}.nupkg
        asset_name: SqlBulkCopyMerge.${{ env.RELEASE_VERSION }}.nupkg
        asset_content_type: application/zip
        
    - name: Push to Nuget
      run: dotnet nuget push packaged/SqlBulkCopyMerge.$RELEASE_VERSION.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

