name: Publish
env:
  RELEASE_VERSION: 0.0.${{github.run_number}}

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
        
    - name: Pack
      run: dotnet pack src/SqlBulkCopyMerge/SqlBulkCopyMerge.csproj -o packaged -c Release -p:PackageVersion=$RELEASE_VERSION -p:PackageID=stevekirks.SqlBulkCopyMerge
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: packaged
        path: packaged
        
    - name: Test
      run: |
          echo "Attempts"
          echo "1 $RELEASE_VERSION"
